# YAML File for SMPy/KaiserSquires/run.py  

# Paths
input_path: "/work/mccleary_group/superbit/union/Abell3411/g/out/Abell3411_g_annular.fits"
k_map_output_path: "/work/mccleary_group/amit.m/convergence/state_of_the_union/Abell3411/g/Abell3411_g_piff.png"
sn_map_output_path: "/work/mccleary_group/amit.m/convergence/state_of_the_union/sn/Abell3411/sn/g/Abell3411_g.png"

# Parameters
resolution: .141                # Pixel resolution of the map in arcminutes

# k-map Plotting
k_vmax: 0.5                        # Max value for color scale in the plot
k_vmin: -0.5                       # Min value for color scale in the plot
k_gaussian_kernel: 2                # Gaussian kernel size for smoothing
k_figsize: [20, 10]                 # Size of the figure (width, height)
k_cmap: 'magma'                     # Colormap for the plot
k_xlabel: 'Right Ascension (deg)'   # Label for x-axis
k_ylabel: 'Declination (deg)'       # Label for y-axis
k_plot_title: 'Convergence Map: Abell3411 G Band with PIFF'       # Title of the plot
k_gridlines: True                     # Add gridlines? (boolean)

# sn-map Plotting
sn_vmax: 0.5                        # Max value for color scale in the plot
sn_vmin: -0.5                       # Min value for color scale in the plot
sn_gaussian_kernel: 2                # Gaussian kernel size for smoothing
sn_figsize: [20, 10]                 # Size of the figure (width, height)
sn_cmap: 'magma'                     # Colormap for the plot
sn_xlabel: 'Right Ascension (deg)'   # Label for x-axis
sn_ylabel: 'Declination (deg)'       # Label for y-axis
sn_plot_title: 'Convergence Map: Abell3411 G Band with PIFF'       # Title of the plot
sn_gridlines: True                     # Add gridlines? (boolean)

# Columns
ra_col: 'ra'                        # Column name for Right Ascension
dec_col: 'dec'                      # Column name for Declination
g1_col: 'g1_Rinv'                   # Column name for first shear component
g2_col: 'g2_Rinv'                   # Column name for second shear component
weight_col: 'weight'  # Column name for data weighting